### ISSUE TITLE
Add-on for status of hotspot

### ISSUE THREAD

**Issue by AnhTuDo1998** [helium/helium-api-rs#51]
Hi, I want to ask if the adding of status received from querying an individual hotspot as shown below is okay?

"status": {
      "height": 394065,
      "online": "offline"
    }

I am looking at using this status in one of my project and has made some changes to `\model`. Would be really keen if I can do a pull request for this. Thank you :)

**Comment by madninja** [comment]
> Hi, I want to ask if the adding of status received from querying an individual hotspot as shown below is okay?
> 
> "status": { "height": 394065, "online": "offline" }
> 
> I am looking at using this status in one of my project and has made some changes to `\model`. Would be really keen if I can do a pull request for this. Thank you :)

Are you referring to this rust library or the actual API?

**Comment by AnhTuDo1998** [comment]
Hi, I am referring to **this** Rust library. The actual API has already returned this status field for hotspot.
 
I took the information from the [API documentation](https://docs.helium.com/api/blockchain/hotspots/). You can see from this screencap below:

![image](https://user-images.githubusercontent.com/32509869/143726873-e8aa090c-c916-4396-a4eb-32582e187e66.png)

When using this library, it seems that the json fields on status was not parsed into struct as no struct for status was defined. Maybe we can do something similar to [Geocode](https://github.com/AnhTuDo1998/helium-api-rs/blob/8b2ca98c2a732b37f8e4f16b460dcf71df6f64a1/src/models/geocode.rs)

**Comment by madninja** [comment]
Ah yes ok.. Yep the hotspot model could be extended with a status field. You want to submit a PR?

**Comment by AnhTuDo1998** [comment]
Yes sure @madninja . 

Is this repository is still under development and that's why not all field from the API response is implemented in the models ?

**Comment by madninja** [comment]
> Yes sure @madninja .
> 
> Is this repository is still under development and that's why not all field from the API response is implemented in the models ?

1. The repo is extended as use cases need it
2. The status field is not ideal since it does not represent actual _onchain_ state and but is gossiped data and as such not considered reliable. 
3. It may be removed or changfed in the not too distant fugure

**Comment by AnhTuDo1998** [comment]
Close as resolved in #52
